name: CI

on:
  # This line allows a user to manually kick off this job from workflows
  workflow_dispatch:
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  Unit_Test:
    runs-on: [ubuntu-latest]
    steps:
      - run: echo "CI pipeline triggered by ${{ github.event_name }} event"
      - run: echo "Running on ${{ runner.os }} server"
      - run: echo "Executing on branch ${{ github.ref }} and repository ${{ github.repository }}"
      # This allows github to access the project in the workspace that it creates
      - name: Check Out Project Files
        uses: actions/checkout@v3
      # This installs a java version in the project workspace created by Github during this action
      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      # Set up Gradle for executing gradle commands. While technically unnecessary, this allows for gradle caching to speed up subsequent workflows
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      # Validate the checksums of the gradle wrapper jar, ensuring no malicious actor has injected code into it
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4
      # Run a gradle command to execute unit tests under the debug variant
      - name: Run Unit tests
        run: ./gradlew testDebugUnitTest
      - name: Report Completion Status
        run: echo "Job complete, status is ${{ job.status }}."
  # This job will contribute a dependency graph generated by gradle to the insights tab of the gradle repository
  # which allows for generation of a SBOM (software bill of materials) on demand via UI
  Generate_SBOM:
    runs-on: [ubuntu-latest]
    # The Dependency Submission API requires write permission
    permissions:
      contents: write
    steps:
      - name: Checkout Project Files
        uses: actions/checkout@v3
      # Validate the checksums of the gradle wrapper jar, ensuring no malicious actor has injected code into it
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4
      # Run a snapshot of the dependencies within the application and submit those dependencies to the
      # insights tab of the Github repository for SBOM generation
      - name: Build dependencies
        run: ./gradlew app:dependencies
      - name: Print Directory Structure After Building Dependencies
        run: |
         cd ../..
         ls -al
      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          path: ../../
          output-file: sbom-android.json
          format: cyclonedx-json