name: CI

on:
  # This line allows a user to manually kick off this job from workflows
  workflow_dispatch:
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  unit_tests:
    runs-on: [ubuntu-latest]
    steps:
      - run: echo "CI pipeline triggered by ${{ github.event_name }} event"
      - run: echo "Running on ${{ runner.os }} server"
      - run: echo "Executing on branch ${{ github.ref }} and repository ${{ github.repository }}"
      # This allows github to access the project in the workspace that it creates
      - name: Check Out Project Files
        uses: actions/checkout@v3
      # This installs a java version in the project workspace created by Github during this action
      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      # Set up Gradle for executing gradle commands. While technically unnecessary, this allows for gradle caching to speed up subsequent workflows
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      # Run a gradle command to execute unit tests under the debug variant
      - name: Run Unit tests
        run: ./gradlew testDebugUnitTest
      - name: Report Completion Status
        run: echo "Job complete, status is ${{ job.status }}."